const test = require("node:test");
const assert = require("node:assert/strict");
const { readFileSync } = require("node:fs");
const { join } = require("node:path");

const { renderHtml } = require("../dist/render-html.js");
const { renderSceneEffectsAuditHtml } = require("../dist/render/render-scene-effects-audit-html.js");
const { renderZOrderAuditHtml } = require("../dist/render-z-order-audit-html.js");

function readClientSource(...segments) {
  return readFileSync(join(__dirname, "../src/client", ...segments), "utf8");
}

function readRuntimeSource(fileName) {
  return readClientSource("runtime", fileName);
}

test("renderHtml loads external client assets and bootstrap config", () => {
  const html = renderHtml({
    host: "127.0.0.1",
    port: 4181,
    explicitProjects: false,
    projects: [{ root: "/tmp/project", label: "project" }]
  });

  assert.match(html, /<link rel="stylesheet" href="\/client\/app\.css\?v=/);
  assert.match(html, /<script src="\/client\/app\.js\?v=.*"><\/script>/);
  assert.match(html, /window\.__AGENTS_OFFICE_CLIENT_CONFIG__/);
  assert.match(html, /"sceneDefinitions":\{/);
});

test("renderHtml can bootstrap a discovered fleet project list distinct from the seed options", () => {
  const html = renderHtml(
    {
      host: "127.0.0.1",
      port: 4181,
      explicitProjects: false,
      projects: [{ root: "/tmp/seed", label: "Seed" }]
    },
    [
      { root: "/tmp/seed", label: "Seed" },
      { root: "/tmp/discovered", label: "Discovered" }
    ]
  );

  assert.match(html, /"root":"\/tmp\/seed","label":"Seed"/);
  assert.match(html, /"root":"\/tmp\/discovered","label":"Discovered"/);
});

test("renderHtml includes the global split-worktrees toggle", () => {
  const html = renderHtml({
    host: "127.0.0.1",
    port: 4181,
    explicitProjects: false,
    projects: [{ root: "/tmp/project", label: "project" }]
  });

  assert.match(html, /id="split-worktrees-button"/);
  assert.match(html, /Split Worktrees/);
});

test("renderHtml includes explicit shared-room save and clear controls", () => {
  const html = renderHtml({
    host: "127.0.0.1",
    port: 4181,
    explicitProjects: false,
    projects: [{ root: "/tmp/project", label: "project" }]
  });

  assert.match(html, /id="multiplayer-save-button"/);
  assert.match(html, /id="multiplayer-clear-button"/);
});

test("renderHtml includes the image-only hat picker controls", () => {
  const html = renderHtml({
    host: "127.0.0.1",
    port: 4181,
    explicitProjects: false,
    projects: [{ root: "/tmp/project", label: "project" }]
  });

  assert.match(html, /id="hat-prev-button"/);
  assert.match(html, /id="hat-preview"/);
  assert.match(html, /id="hat-next-button"/);
});

test("z-order audit html exposes the visual workstation overlap harness", () => {
  const html = renderZOrderAuditHtml();

  assert.match(html, /Z-Order Audit/);
  assert.match(html, /Motion Sweep/);
  assert.match(html, /Front Edge/);
  assert.match(html, /data-sweep/);
  assert.match(html, /requestAnimationFrame\(tick\);/);
  assert.match(html, /avatar stays behind workstation/);
  assert.match(html, /same <code>sceneFootDepth\(\)<\/code> math as the app/);
  assert.match(html, /Pixi still sorts by <code>zIndex<\/code>/);
  assert.match(html, /\/z-order-audit/);
});

test("scene effects audit html mocks approval and input waits through the normal client bundle", () => {
  const html = renderSceneEffectsAuditHtml();

  assert.match(html, /Scene Effects Audit/);
  assert.match(html, /mocked typed Codex approval\/input fleet data/);
  assert.match(html, /audit-thread-approval-command/);
  assert.match(html, /audit-request-input/);
  assert.match(html, /Ready to dry-run publish once you approve the command\./);
  assert.match(html, /I need launch mode, a note, and the deploy token to proceed\./);
  assert.match(html, /window\.fetch = \(input, init = undefined\)/);
  assert.match(html, /window\.EventSource = MockEventSource/);
  assert.match(html, /\/client\/app\.js\?v=/);
});

test("client bootstrap runs the generated runtime module instead of evaling a source string", () => {
  const indexSource = readClientSource("index.ts");
  const runtimeModuleSource = readClientSource("app-runtime.ts");

  assert.ok(indexSource.includes('import { startClientApp } from "./app-runtime";'));
  assert.ok(indexSource.includes("startClientApp();"));
  assert.doesNotMatch(indexSource, /new Function\(/);
  assert.match(
    runtimeModuleSource,
    /^\/\/ @ts-nocheck\n\/\/ Generated by packages\/web\/scripts\/generate-runtime-module\.mjs/m
  );
  assert.ok(runtimeModuleSource.includes("export function startClientApp(): void {"));
});

test("client runtime keeps current local desk-live work on a workstation through notLoaded transport gaps", () => {
  const layoutSource = readRuntimeSource("layout-source.ts");
  const seatingSource = readRuntimeSource("seating-source.ts");

  assert.doesNotMatch(layoutSource, /const CURRENT_LOCAL_LIVE_WORKSTATION_GRACE_MS = 8000;/);
  assert.doesNotMatch(layoutSource, /return agent\.isOngoing === true \|\| hasCurrentLocalDeskGrace\(agent\);/);
  assert.match(
    seatingSource,
    /const CURRENT_LOCAL_LIVE_WORKSTATION_GRACE_MS = 8000;/
  );
  assert.match(
    seatingSource,
    /const QUIET_LIVE_LOCAL_WORKSTATION_GRACE_MS = 3 \* 60 \* 1000;/
  );
  assert.match(
    seatingSource,
    /function hasCurrentLocalDeskGrace\(agent, maxAgeMs = CURRENT_LOCAL_LIVE_WORKSTATION_GRACE_MS\) {\n\s+const updatedAt = parseAgentUpdatedAt\(agent && agent\.updatedAt\);/
  );
  assert.match(
    seatingSource,
    /if \(agent\.statusText === "notLoaded"\) {\n\s+if \(agent\.state === "done"\) {\n\s+const updatedAt = parseAgentUpdatedAt\(agent\.updatedAt\);/
  );
  assert.match(
    seatingSource,
    /return agent\.isCurrent === true\n\s+&& Number\.isFinite\(updatedAt\)\n\s+&& Date\.now\(\) - updatedAt <= Math\.max\(workstationDoneGraceMs\(agent\), QUIET_LIVE_LOCAL_WORKSTATION_GRACE_MS\);/
  );
  assert.match(
    seatingSource,
    /return agent\.isOngoing === true\n\s+\|\| agent\.isCurrent === true\n\s+\|\| hasCurrentLocalDeskGrace\(agent, QUIET_LIVE_LOCAL_WORKSTATION_GRACE_MS\);/
  );
});

test("client runtime keeps active local desks live, keeps waiting on-desk, and gives current idle/done work a short settle window", () => {
  const layoutSource = readRuntimeSource("layout-source.ts");
  const seatingSource = readRuntimeSource("seating-source.ts");

  assert.doesNotMatch(layoutSource, /if \(agent\.state === "waiting"\) {\n\s+return false;\n\s+}/);
  assert.match(
    layoutSource,
    /function isDeskLiveLocalState\(state\) {\n\s+return \[\n(?:.*\n)*?\s+"waiting",\n\s+"blocked"\n\s+\]\.includes\(String\(state \|\| ""\)\.toLowerCase\(\)\);/
  );
  assert.doesNotMatch(seatingSource, /if \(agent\.state === "waiting"\) {\n\s+return false;\n\s+}/);
  assert.match(
    seatingSource,
    /function hasCurrentLocalSeatCooldown\(agent\) {\n\s+const updatedAt = parseAgentUpdatedAt\(agent && agent\.updatedAt\);/
  );
  assert.match(
    seatingSource,
    /if \(agent\.statusText === "active"\) {\n\s+if \(isRuntimeActiveLocalAgent\(agent\)\) {\n\s+return true;\n\s+}\n\s+if \(\(agent\.state === "idle" \|\| agent\.state === "done"\) && hasCurrentLocalSeatCooldown\(agent\)\) {\n\s+return true;\n\s+}\n\s+return agent\.isCurrent === true\n\s+&& agent\.state !== "idle"\n\s+&& agent\.state !== "done";/
  );
  assert.match(
    seatingSource,
    /if \(agent\.isOngoing === true\) {\n\s+return true;\n\s+}\n\s+if \(agent\.isCurrent === true\) {\n\s+return true;\n\s+}\n\s+if \(agent\.state === "done"\) {\n\s+return agent\.isCurrent === true;\n\s+}/
  );
});

test("client runtime seats current local workload even when its latest item summarizes idle", () => {
  const seatingSource = readRuntimeSource("seating-source.ts");

  assert.match(
    seatingSource,
    /if \(agent\.isOngoing === true\) {\n\s+return true;\n\s+}\n\s+if \(agent\.isCurrent === true\) {\n\s+return true;\n\s+}\n\s+if \(agent\.state === "done"\) {/
  );
});

test("client runtime gives finished subagents a longer workstation cooldown than leads", () => {
  const seatingSource = readRuntimeSource("seating-source.ts");

  assert.match(seatingSource, /const TOP_LEVEL_DONE_WORKSTATION_GRACE_MS = 3000;/);
  assert.match(seatingSource, /const SUBAGENT_DONE_WORKSTATION_GRACE_MS = 7000;/);
  assert.match(
    seatingSource,
    /return agent && agent\.parentThreadId\s+\? SUBAGENT_DONE_WORKSTATION_GRACE_MS\s+\: TOP_LEVEL_DONE_WORKSTATION_GRACE_MS;/
  );
});

test("client runtime only keeps ordinary local desks for current workload", () => {
  const layoutSource = readRuntimeSource("layout-source.ts");
  const seatingSource = readRuntimeSource("seating-source.ts");

  assert.match(seatingSource, /if \(agent\.isCurrent !== true\) {\n\s+return false;/);
  assert.doesNotMatch(layoutSource, /if \(agent\.isCurrent !== true\) {\n\s+return false;/);
  assert.doesNotMatch(seatingSource, /const recentlyLive = Number\.isFinite\(updatedAt\)/);
});

test("runtime source keeps desk seats stable when a second workstation appears in a pod", () => {
  const sceneSource = readRuntimeSource("scene-source.ts");

  assert.ok(sceneSource.includes("const tile = sceneTileSize(compact);"));
  assert.ok(sceneSource.includes("const leftCellX = 0;"));
  assert.ok(sceneSource.includes("const rightCellX = Math.max(0, entry.slot.width - cellWidth);"));
  assert.ok(sceneSource.includes("const seatMirrored = hasBothSides"));
  assert.ok(sceneSource.includes("const cellX = seatMirrored ? rightCellX : leftCellX;"));
  assert.ok(sceneSource.includes("mirrored: seatMirrored,"));
});

test("runtime source keeps running and validating workers seated at their workstation", () => {
  const renderSource = readRuntimeSource("render-source.ts");

  assert.ok(renderSource.includes('if (state === "running" || state === "validating") {'));
  assert.ok(renderSource.includes('if (state === "blocked") {'));
  assert.ok(renderSource.includes('state === "delegating" || state === "waiting"'));
  assert.ok(renderSource.includes("tileHeight: 2"));
});

test("runtime source adds above-head state markers for needs-user, thinking, planning, and blocked-error states", () => {
  const renderSource = readRuntimeSource("render-source.ts");
  const navigationSource = readRuntimeSource("navigation-source.ts");
  const sceneSource = readRuntimeSource("scene-source.ts");

  assert.ok(renderSource.includes('function stateMarkerIconUrlForAgent(agent) {'));
  assert.ok(renderSource.includes('function shouldShowThinkingMarker(agent) {'));
  assert.ok(renderSource.includes('agent.activityEvent && agent.activityEvent.type === "agentMessage"'));
  assert.ok(renderSource.includes('agent.latestMessage.trim().length > 0'));
  assert.ok(renderSource.includes('return "/assets/pixel-office/sprites/icons/state/hand.png";'));
  assert.ok(renderSource.includes('return "/assets/pixel-office/sprites/icons/state/exclamation.png";'));
  assert.ok(renderSource.includes('return "/assets/pixel-office/sprites/icons/state/clipboard.png";'));
  assert.ok(renderSource.includes('return "/assets/pixel-office/sprites/icons/state/light.png";'));
  assert.ok(navigationSource.includes("const STATE_MARKER_SIZE = 11;"));
  assert.ok(navigationSource.includes("const STATE_MARKER_BUBBLE_Y_OFFSET = 20;"));
  assert.ok(sceneSource.includes("Math.max(8, Math.round(entry.statusMarker.width || 11))"));
  assert.ok(navigationSource.includes("const statusMarkerUrl = agent.statusMarkerIconUrl || stateMarkerIconUrlForAgent(agent);"));
  assert.ok(sceneSource.includes("statusMarkerIconUrl: stateMarkerIconUrlForAgent(agent),"));
  assert.ok(sceneSource.includes("statusMarkerIconUrl: stateMarkerIconUrlForAgent(entry.agent),"));
});

test("runtime source adds transient turn-phase badges for started, completed, interrupted, and failed turns", () => {
  const renderSource = readRuntimeSource("render-source.ts");
  const navigationSource = readRuntimeSource("navigation-source.ts");
  const sceneSource = readRuntimeSource("scene-source.ts");

  assert.ok(renderSource.includes("const TURN_SIGNAL_MAX_AGE_MS = 6000;"));
  assert.ok(renderSource.includes("function recentTurnSignalForAgent(snapshot, agent) {"));
  assert.ok(renderSource.includes('return "START";'));
  assert.ok(renderSource.includes('return "DONE";'));
  assert.ok(renderSource.includes('return "STOP";'));
  assert.ok(renderSource.includes('return "FAIL";'));
  assert.ok(sceneSource.includes("turnSignal: recentTurnSignalForAgent(snapshot, agent),"));
  assert.ok(sceneSource.includes("turnSignal: recentTurnSignalForAgent(snapshot, entry.agent),"));
  assert.ok(navigationSource.includes("const TURN_SIGNAL_PADDING_X = 4;"));
  assert.ok(navigationSource.includes("function turnSignalPalette(signal) {"));
  assert.ok(navigationSource.includes("function syncTurnSignalNode(motionState, turnSignal, liftPx = 0) {"));
  assert.ok(navigationSource.includes('kind: "turn-signal",'));
  assert.ok(sceneSource.includes('if (entry.kind === "turn-signal") {'));
});

test("runtime source maps recent typed plan, command, file, and tool events into transient activity cues", () => {
  const renderSource = readRuntimeSource("render-source.ts");
  const navigationSource = readRuntimeSource("navigation-source.ts");
  const sceneSource = readRuntimeSource("scene-source.ts");

  assert.ok(renderSource.includes("const ACTIVITY_CUE_MAX_AGE_MS = 4800;"));
  assert.ok(renderSource.includes("function activityCueForEvent(event) {"));
  assert.ok(renderSource.includes('return { mode: "plan", label: "PLAN" };'));
  assert.ok(renderSource.includes('return { mode: "command", label: "RUN" };'));
  assert.ok(renderSource.includes('return { mode: "file", label: "EDIT" };'));
  assert.ok(renderSource.includes('return { mode: "tool", label: "TOOL" };'));
  assert.ok(renderSource.includes("function recentActivityCueForAgent(snapshot, agent) {"));
  assert.ok(sceneSource.includes("activityCue: recentActivityCueForAgent(snapshot, agent),"));
  assert.ok(sceneSource.includes("activityCue: recentActivityCueForAgent(snapshot, entry.agent),"));
  assert.ok(navigationSource.includes("function activityCuePalette(cue) {"));
  assert.ok(navigationSource.includes("function buildActivityCueAdornment(mode, palette) {"));
  assert.ok(navigationSource.includes('return cue.mode === "plan"'));
  assert.ok(navigationSource.includes("function syncActivityCueNode(motionState, activityCue, driftX = 0, driftY = 0) {"));
  assert.ok(navigationSource.includes('kind: "activity-cue",'));
  assert.ok(sceneSource.includes('if (entry.kind === "activity-cue") {'));
});

test("runtime source maps approval waits, input waits, and resolved requests into transient lifecycle cues", () => {
  const renderSource = readRuntimeSource("render-source.ts");
  const navigationSource = readRuntimeSource("navigation-source.ts");
  const sceneSource = readRuntimeSource("scene-source.ts");

  assert.ok(renderSource.includes('return { mode: "approval", label: "WAIT" };'));
  assert.ok(renderSource.includes('return { mode: "input", label: "ASK" };'));
  assert.ok(renderSource.includes('return { mode: "resolved", label: "OK" };'));
  assert.ok(navigationSource.includes('if (cue.mode === "approval" || cue.mode === "input") {'));
  assert.ok(navigationSource.includes('if (cue.mode === "resolved") {'));
  assert.ok(sceneSource.includes('entry.mode === "approval" ? Math.round(Math.sin((now + entry.phase) / 150) * 1.4)'));
  assert.ok(sceneSource.includes('entry.mode === "input" ? -Math.round(progress * 3 + Math.sin((now + entry.phase) / 130) * 1.4)'));
  assert.ok(sceneSource.includes('entry.mode === "resolved" ? -Math.round(progress * 7 + Math.sin((now + entry.phase) / 150) * 1.2)'));
});

test("activity cues include mode-specific icon adornments and icon-side animation, not just text chips", () => {
  const navigationSource = readRuntimeSource("navigation-source.ts");
  const sceneSource = readRuntimeSource("scene-source.ts");

  assert.ok(navigationSource.includes("const ACTIVITY_CUE_ICON_WIDTH = 8;"));
  assert.ok(navigationSource.includes("const ACTIVITY_CUE_ICON_GAP = 3;"));
  assert.ok(navigationSource.includes("function activityCueFrameRadius(mode) {"));
  assert.ok(navigationSource.includes('return mode === "command" || mode === "file" ? 1 : 4;'));
  assert.ok(navigationSource.includes("fillColor: 0x080c10,"));
  assert.ok(navigationSource.includes("fillColor: 0x101714,"));
  assert.ok(navigationSource.includes('if (mode === "plan") {'));
  assert.ok(navigationSource.includes('} else if (mode === "command") {'));
  assert.ok(navigationSource.includes('} else if (mode === "file") {'));
  assert.ok(navigationSource.includes('} else if (mode === "tool") {'));
  assert.ok(navigationSource.includes('} else if (mode === "approval") {'));
  assert.ok(navigationSource.includes('} else if (mode === "input") {'));
  assert.ok(navigationSource.includes('} else if (mode === "resolved") {'));
  assert.ok(navigationSource.includes("activityCueContainer.addChild(adornment.iconContainer);"));
  assert.ok(navigationSource.includes("iconContainer,"));
  assert.ok(sceneSource.includes('if (cueIcon && entry.mode === "plan") {'));
  assert.ok(sceneSource.includes('} else if (cueIcon && entry.mode === "tool") {'));
  assert.ok(sceneSource.includes('cueIcon.rotation = (now + entry.phase) / 420;'));
  assert.ok(sceneSource.includes('cueAccent.rotation = (now + entry.phase) / 260;'));
});

test("recent workstation activity also creates non-text desk effects beyond the floating cue chip", () => {
  const renderSource = readRuntimeSource("render-source.ts");
  const navigationSource = readRuntimeSource("navigation-source.ts");
  const sceneSource = readRuntimeSource("scene-source.ts");

  assert.ok(renderSource.includes("function requestCueProfileForAgent(agent, cue, event = null) {"));
  assert.ok(renderSource.includes("requestProfile: requestCueProfileForAgent(agent, cue, event),"));
  assert.ok(renderSource.includes("decisionCount,"));
  assert.ok(renderSource.includes("approvalType"));
  assert.ok(renderSource.includes("questionCount: Math.max(1, Math.min(4, questions.length || 1))"));
  assert.ok(renderSource.includes("requiredCount: Math.max(0, Math.min(4, requiredCount))"));
  assert.ok(renderSource.includes("function buildWorkstationCueEffect(cue, absoluteCellX, absoluteCellY, workstationX, workstationY, workstationWidth, workstationHeight, workstationSortRow, workstationSortFootY, options = {}) {"));
  assert.ok(renderSource.includes('kind: "cue-effect",'));
  assert.ok(renderSource.includes("requestProfile: cue.requestProfile || null,"));
  assert.ok(renderSource.includes("const workstationCueEffect = buildWorkstationCueEffect("));
  assert.ok(renderSource.includes("shell.push(workstationCueEffect);"));
  assert.ok(navigationSource.includes("function buildWorkstationCueEffectNode(effect) {"));
  assert.ok(navigationSource.includes("const requestProfile = effect && effect.requestProfile && typeof effect.requestProfile === \"object\""));
  assert.ok(navigationSource.includes("const decisionCount = Math.max(2, Math.min(4, Number(requestProfile && requestProfile.decisionCount) || 3));"));
  assert.ok(navigationSource.includes("const questionCount = Math.max(1, Math.min(4, Number(requestProfile && requestProfile.questionCount) || 3));"));
  assert.ok(navigationSource.includes("detailNodes,"));
  assert.ok(navigationSource.includes('if (item.kind === "cue-effect") {'));
  assert.ok(navigationSource.includes('kind: "workstation-cue-effect",'));
  assert.ok(sceneSource.includes('if (entry.kind === "workstation-cue-effect") {'));
  assert.ok(sceneSource.includes("const approvalProfile = entry.requestProfile && typeof entry.requestProfile === \"object\""));
  assert.ok(sceneSource.includes("const inputProfile = entry.requestProfile && typeof entry.requestProfile === \"object\""));
  assert.ok(sceneSource.includes("index < requiredCount"));
  assert.ok(sceneSource.includes('entry.mode === "command") {'));
  assert.ok(sceneSource.includes('entry.mode === "resolved") {'));
});

test("runtime source lets scene-agent clicks open a stable thread history card", () => {
  const settingsSource = readRuntimeSource("settings-source.ts");
  const renderSource = readRuntimeSource("render-source.ts");
  const sceneSource = readRuntimeSource("scene-source.ts");
  const navigationSource = readRuntimeSource("navigation-source.ts");
  const uiSource = readRuntimeSource("ui-source.ts");
  const stylesSource = readClientSource("styles.css");

  assert.ok(settingsSource.includes("openAgentThread: null,"));
  assert.ok(settingsSource.includes("closingAgentThread: null,"));
  assert.ok(settingsSource.includes("replyThreadWorkIntents: {},"));
  assert.ok(settingsSource.includes("expandedThreadEntries: {},"));
  assert.ok(renderSource.includes("function recentThreadHistoryEntries(snapshot, agent) {"));
  assert.ok(renderSource.includes("function renderAgentThreadCard(snapshot, agent, options = {}) {"));
  assert.ok(renderSource.includes("function renderThreadHistoryEntry(snapshot, agent, entry) {"));
  assert.ok(renderSource.includes("function threadEntryLooksLong(body) {"));
  assert.ok(renderSource.includes('data-action="toggle-thread-entry"'));
  assert.ok(renderSource.includes('data-thread-entry-key='));
  assert.ok(renderSource.includes('key: ["latest", agent.threadId].join("::"),'));
  assert.ok(renderSource.includes('const cardClass = options.closing ? "office-map-thread-card is-closing" : "office-map-thread-card";'));
  assert.ok(renderSource.includes("Thread history"));
  assert.ok(!renderSource.includes("office-map-thread-composer"));
  assert.ok(!renderSource.includes("renderThreadResumeComposerForThread"));
  assert.ok(sceneSource.includes("threadPanel: null"));
  assert.ok(sceneSource.includes("function registerThreadPanel(agent) {"));
  assert.ok(sceneSource.includes("function openThreadStageOffset(agent) {"));
  assert.ok(sceneSource.includes("renderAgentThreadCard(snapshot, agent, { closing: panelState === \"closing\" })"));
  assert.ok(sceneSource.includes("const projectRoot = threadViewProjectRoot(snapshot, agent);"));
  assert.ok(sceneSource.includes("replyProjectRoot: threadViewProjectRoot(snapshot, agent) || \"\","));
  assert.ok(sceneSource.includes("replyProjectRoot: threadViewProjectRoot(snapshot, entry.agent) || \"\","));
  assert.ok(sceneSource.includes("threadOpen: Boolean(sceneThreadPanelState(agent))"));
  assert.ok(sceneSource.includes("hoverHtml: openThreadSuppressesHover ? \"\" : renderAgentHover(snapshot, agent)"));
  assert.ok(sceneSource.includes('data-office-map-thread-layer'));
  assert.ok(navigationSource.includes('class="office-map-agent-trigger" data-action="open-agent-thread"'));
  assert.ok(navigationSource.includes("node.classList.add(\"is-thread-open\");"));
  assert.ok(navigationSource.includes("renderer.threadLayer"));
  assert.ok(navigationSource.includes('className = "office-map-thread-panel-slot"'));
  assert.ok(navigationSource.includes("function syncThreadPanel(renderer, model) {"));
  assert.ok(navigationSource.includes("function syncThreadHistory(history, nextHistory) {"));
  assert.ok(navigationSource.includes("function threadHistoryAtBottom(history) {"));
  assert.ok(navigationSource.includes("fresh.classList.add(\"is-new\");"));
  assert.ok(navigationSource.includes("function officeSceneRenderToken(snapshot, options = {}) {"));
  assert.ok(navigationSource.includes("if (renderer.sceneRenderToken !== renderToken) {"));
  assert.ok(navigationSource.includes("syncOfficeAnchors(renderer, model, renderer.scale || 1);"));
  assert.ok(uiSource.includes("function openAgentThread(projectRoot, threadId) {"));
  assert.ok(uiSource.includes("state.openAgentThread.projectRoot === projectRoot"));
  assert.ok(uiSource.includes("render();\n          return;\n        }\n        state.openAgentThread = {"));
  assert.ok(uiSource.includes("state.openAgentThread = {\n          projectRoot,\n          threadId\n        };\n        render();"));
  assert.ok(uiSource.includes("function threadViewProjectRoot(snapshot, agent) {"));
  assert.ok(uiSource.includes("function findThreadViewEntry(projectRoot, threadId) {"));
  assert.ok(uiSource.includes('agent.sourceKind !== "appServer"'));
  assert.ok(uiSource.includes("&& !findThreadViewEntry(state.openAgentThread.projectRoot, state.openAgentThread.threadId)"));
  assert.ok(uiSource.includes("function markReplyThreadWorkIntent(threadId"));
  assert.ok(uiSource.includes("function toggleThreadEntryExpanded(stateKey) {"));
  assert.ok(!uiSource.includes("renderThreadResumeComposerForThread"));
  assert.ok(!uiSource.includes('data-action="open-thread-resume"'));
  assert.ok(!uiSource.includes('data-action="copy-resume-command"'));
  assert.ok(!uiSource.includes("/api/thread/open-resume"));
  assert.ok(uiSource.includes("const THREAD_REPLY_TIMEOUT_MS = 90000;"));
  assert.ok(uiSource.includes("}, THREAD_REPLY_TIMEOUT_MS);"));
  assert.ok(uiSource.includes("if (action === \"open-agent-thread\" && target.dataset.projectRoot && target.dataset.threadId) {"));
  assert.ok(uiSource.includes("if (action === \"close-agent-thread\") {"));
  assert.ok(uiSource.includes("if (action === \"toggle-thread-entry\" && target.dataset.threadEntryStateKey) {"));
  assert.ok(uiSource.includes("event.key === \"Enter\""));
  assert.ok(uiSource.includes("&& !event.shiftKey"));
  assert.ok(uiSource.includes("void submitReplyComposer(event.target.dataset.replyProjectRoot, event.target.dataset.replyThreadId);"));
  assert.ok(uiSource.includes("if (event.key === \"Escape\" && state.openAgentThread) {"));
  assert.ok(stylesSource.includes(".office-map-thread-card {"));
  assert.ok(stylesSource.includes(".office-map-thread-layer {"));
  assert.ok(stylesSource.includes(".office-map-host.has-thread-panel .office-map-agent-hit:hover .agent-hover"));
  assert.ok(stylesSource.includes("@keyframes officeThreadPanelIn"));
  assert.ok(stylesSource.includes("@keyframes officeThreadPanelOut"));
  assert.ok(stylesSource.includes("@keyframes officeThreadMessageIn"));
  assert.ok(stylesSource.includes(".office-map-thread-body.is-collapsed {"));
  assert.ok(stylesSource.includes("-webkit-line-clamp: 8;"));
  assert.ok(stylesSource.includes(".office-map-thread-more {"));
  assert.ok(stylesSource.includes(".office-map-thread-icon {"));
  assert.ok(stylesSource.includes(".office-map-thread-window-bar {"));
  assert.ok(stylesSource.includes(".office-map-agent-trigger {"));
  assert.ok(stylesSource.includes(".office-map-thread-history {"));
});

test("runtime source adds stronger state-specific animation for waiting, blocked, and validating work", () => {
  const renderSource = readRuntimeSource("render-source.ts");
  const navigationSource = readRuntimeSource("navigation-source.ts");
  const sceneSource = readRuntimeSource("scene-source.ts");

  assert.ok(renderSource.includes('color: state === "validating" ? 0x69c7ff : 0x4bd69f,'));
  assert.ok(renderSource.includes('pulse: state === "validating",'));
  assert.ok(navigationSource.includes("function stateEffectModeForAgent(agent) {"));
  assert.ok(navigationSource.includes('return "waiting";'));
  assert.ok(navigationSource.includes('return "blocked";'));
  assert.ok(navigationSource.includes("function syncStateEffectNode(entry, now) {"));
  assert.ok(navigationSource.includes('kind: "workstation-glow",'));
  assert.ok(navigationSource.includes('kind: "state-effect",'));
  assert.ok(sceneSource.includes('if (entry.kind === "workstation-glow") {'));
  assert.ok(sceneSource.includes('if (entry.kind === "state-effect") {'));
});

test("runtime source gives seated active states distinct motion profiles instead of one generic bob", () => {
  const navigationSource = readRuntimeSource("navigation-source.ts");
  const sceneSource = readRuntimeSource("scene-source.ts");

  assert.ok(navigationSource.includes('stateValue === "planning" ? "planning"'));
  assert.ok(navigationSource.includes('stateValue === "scanning" ? "scanning"'));
  assert.ok(navigationSource.includes('stateValue === "editing" ? "editing"'));
  assert.ok(navigationSource.includes('stateValue === "running" ? "running"'));
  assert.ok(navigationSource.includes('stateValue === "validating" ? "validating"'));
  assert.ok(navigationSource.includes('stateValue === "delegating" ? "delegating"'));
  assert.ok(navigationSource.includes("baseX: pixelSnap(avatarVisual.avatar && avatarVisual.avatar.x),"));
  assert.ok(navigationSource.includes("mode,"));
  assert.ok(sceneSource.includes('bobMode === "planning" ? Math.round(waveSlow * 1)'));
  assert.ok(sceneSource.includes('bobMode === "scanning" ? Math.round(waveMid * 1.4)'));
  assert.ok(sceneSource.includes('bobMode === "editing" ? Math.round(waveFast * 1.6)'));
  assert.ok(sceneSource.includes('bobMode === "running" ? Math.round((waveFast + waveStep * 0.45) * 1.7)'));
  assert.ok(sceneSource.includes('bobMode === "validating" ? Math.round(waveMid * 0.8)'));
  assert.ok(sceneSource.includes('bobMode === "delegating" ? Math.round((waveSlow + waveMid * 0.45) * 1.3)'));
});

test("runtime source adds completion summaries and clear actions for multi-question Needs You inputs", () => {
  const navigationSource = readRuntimeSource("navigation-source.ts");
  const uiSource = readRuntimeSource("ui-source.ts");

  assert.ok(navigationSource.includes("function needsUserInputCompletion(need) {"));
  assert.ok(navigationSource.includes('return header || "Question " + (questionIndex + 1);'));
  assert.ok(navigationSource.includes('return "Still needed: " + completion.missingRequired[0];'));
  assert.ok(navigationSource.includes('data-action="clear-needs-user-answer"'));
  assert.ok(navigationSource.includes('escapeHtml(needsUserInputSummary(need))'));
  assert.ok(navigationSource.includes('escapeHtml(needsUserInputSubmitLabel(need, isPending))'));
  assert.ok(uiSource.includes('if (action === "clear-needs-user-answer" && target.dataset.needsUserRequestId && target.dataset.needsUserQuestionId) {'));
  assert.ok(uiSource.includes("const completion = needsUserInputCompletion(entry.need);"));
});

test("runtime source lets queue items open inline reply composers for general local Codex input prompts", () => {
  const navigationSource = readRuntimeSource("navigation-source.ts");
  const uiSource = readRuntimeSource("ui-source.ts");

  assert.ok(navigationSource.includes("const canReplyToInput = Boolean("));
  assert.ok(navigationSource.includes('data-action="open-reply-composer"'));
  assert.ok(navigationSource.includes('renderReplyComposerForThread(replyProjectRoot, agent.threadId, "Reply to this input...")'));
  assert.ok(uiSource.includes("function replyComposerMatchesThread(projectRoot, threadId) {"));
  assert.ok(uiSource.includes("function renderReplyComposerForThread(projectRoot, threadId, placeholder = \"Send a follow-up to this session...\") {"));
});

test("runtime source preserves workstation entering-reveal flags for the Pixi flicker animation", () => {
  const sceneSource = readRuntimeSource("scene-source.ts");
  const navigationSource = readRuntimeSource("navigation-source.ts").replace(/\r\n/g, "\n");

  assert.ok(sceneSource.includes("enteringReveal: options.enteringReveal === true,"));
  assert.ok(sceneSource.includes("enteringReveal: shouldRevealWorkstation(snapshot.projectRoot, agent, entry.slot.id),"));
  assert.ok(sceneSource.includes("enteringReveal: shouldRevealWorkstation(snapshot.projectRoot, entry.agent, entry.slot.id),"));
  assert.ok(sceneSource.includes("function shouldRevealWorkstation(projectRoot, agent, slotId) {"));
  assert.ok(sceneSource.includes("const previousSceneState = renderedAgentSceneState.get(key) || null;"));
  assert.ok(sceneSource.includes("return previousSlotId !== slotId;"));
  assert.ok(
    navigationSource.includes('if (!screenshotMode && definition.enteringReveal === true) {\n            sprite.visible = false;\n          }')
  );
  assert.ok(
    /renderer\.animatedSprites\.push\(\{\s+kind: "blink",\s+nodes: enteringRevealNodes,/m.test(navigationSource)
  );
});

test("blocked failure hover summaries prefer the current error detail over stale latest messages", () => {
  const renderSource = readRuntimeSource("render-source.ts");
  const stylesSource = readClientSource("styles-source.ts");

  assert.ok(renderSource.includes("if (isFailureBlockedAgent(agent) && detail) {"));
  assert.ok(renderSource.includes('return { text: detail, source: "agent", emphasis: "error" };'));
  assert.ok(renderSource.includes('"agent-hover-summary agent-hover-summary-error"'));
  assert.ok(stylesSource.includes(".agent-hover-summary-error {"));
});

test("multiplayer runtime persists per-project sharing and cools remote-only projects for one hour", () => {
  const bootstrapSource = readRuntimeSource("bootstrap-source.ts");
  const settingsSource = readRuntimeSource("settings-source.ts");
  const uiSource = readRuntimeSource("ui-source.ts");
  const multiplayerSource = readClientSource("multiplayer-source.ts");

  assert.ok(bootstrapSource.includes('multiplayerProjectShareStorageKey = \\"codex-agents-office:multiplayer-project-shares\\";'));
  assert.ok(bootstrapSource.includes('appearance: {\\n          hatId: null\\n        },'));
  assert.ok(bootstrapSource.includes('deviceId: \\"\\"'));
  assert.ok(settingsSource.includes("multiplayerProjectShares: loadMultiplayerProjectShares(),"));
  assert.ok(settingsSource.includes("function effectiveHatIdForAgent(agent) {"));
  assert.ok(settingsSource.includes("multiplayerDraft: { ...defaultIntegrationSettings().multiplayer },"));
  assert.ok(multiplayerSource.includes("const MULTIPLAYER_REMOTE_PROJECT_COOLDOWN_MS = 60 * 60 * 1000;"));
  assert.ok(multiplayerSource.includes("function normalizeMultiplayerSettings(settings, options = {}) {"));
  assert.ok(multiplayerSource.includes("const deviceId = sanitizeMultiplayerField(settings && settings.deviceId);"));
  assert.ok(multiplayerSource.includes("const fallbackEnabled = options && typeof options.fallbackEnabled === \"boolean\""));
  assert.ok(multiplayerSource.includes("function currentMultiplayerDeviceId() {"));
  assert.ok(multiplayerSource.includes("function syncStoredMultiplayerSettings(settings) {"));
  assert.ok(multiplayerSource.includes("function loadMultiplayerProjectShares() {"));
  assert.ok(multiplayerSource.includes("function setProjectRootsSharedWithRoom(projectRoots, shared) {"));
  assert.ok(multiplayerSource.includes("function cooledRemoteProjectSnapshot(entry) {"));
  assert.ok(multiplayerSource.includes("Shared project cooldown · keep remote-only floors visible for up to 1 hour after sharing stops."));
  assert.ok(multiplayerSource.includes(".filter((snapshot) => isProjectSharedWithRoom(snapshot.projectRoot))"));
  assert.ok(multiplayerSource.includes("const localHatId = currentSelectedHatId();"));
  assert.ok(multiplayerSource.includes("hatId: localHatId"));
  assert.ok(multiplayerSource.includes("deviceId: currentMultiplayerDeviceId(),"));
  assert.ok(multiplayerSource.includes("payload.deviceId === currentMultiplayerDeviceId()"));
  assert.ok(uiSource.includes('applyIntegrationSettingsResponse(await postJson("/api/settings/integrations", {'));
  assert.ok(uiSource.includes('multiplayerHostInput.addEventListener("input", () => {'));
  assert.ok(uiSource.includes('multiplayerSaveButton.addEventListener("click", () => {'));
  assert.ok(multiplayerSource.includes("const previousConfigured = Boolean("));
  assert.ok(multiplayerSource.includes("const fallbackEnabled = previousConfigured"));
});

test("workspace floors show multiplayer participants, grey remote-only titles, and expose a shared toggle", () => {
  const settingsSource = readRuntimeSource("settings-source.ts");
  const sceneSource = readRuntimeSource("scene-source.ts");
  const uiSource = readRuntimeSource("ui-source.ts");
  const styles = readClientSource("styles.css");

  assert.ok(settingsSource.includes("function sharedParticipantLabelsForSnapshot(snapshot) {"));
  assert.ok(sceneSource.includes('class="tower-floor-participants"'));
  assert.ok(sceneSource.includes('data-action="toggle-project-share"'));
  assert.ok(sceneSource.includes('const remoteOnlyTitleClass = snapshotHasLocalProject(snapshot) ? "" : " is-remote-only";'));
  assert.ok(uiSource.includes('if (action === "toggle-project-share") {'));
  assert.ok(styles.includes(".tower-floor-title.is-remote-only .tower-floor-title-project {"));
  assert.ok(styles.includes(".tower-floor-participants {"));
  assert.ok(styles.includes(".tower-floor-share.active {"));
});

test("runtime source exposes hat preview controls and hat-attached avatar rendering", () => {
  const layoutSource = readRuntimeSource("layout-source.ts");
  const navigationSource = readRuntimeSource("navigation-source.ts");
  const sceneSource = readRuntimeSource("scene-source.ts");
  const uiSource = readRuntimeSource("ui-source.ts");
  const styles = readClientSource("styles.css");

  assert.ok(layoutSource.includes('const hatPrevButton = document.getElementById("hat-prev-button");'));
  assert.ok(layoutSource.includes("function syncAppearanceSettingsUi() {"));
  assert.ok(uiSource.includes("function applyOptimisticHatSelection(hatId) {"));
  assert.ok(uiSource.includes("function cycleHatSelection(direction) {"));
  assert.ok(layoutSource.includes("hatPrevButton.disabled = entries.length <= 1;"));
  assert.ok(uiSource.includes("state.appearanceSettingsPending = true;"));
  assert.ok(navigationSource.includes("function hatRenderMetrics(agent, avatarMetrics) {"));
  assert.ok(navigationSource.includes("function hatRenderX(baseX, centeredOffsetX, manualOffsetX, flipX) {"));
  assert.ok(navigationSource.includes("function buildBobAnimationEntry(agent, avatarVisual, motionState) {"));
  assert.ok(navigationSource.includes("hatSprite"));
  assert.ok(sceneSource.includes("(entry.flipX ? -hatManualOffsetX : hatManualOffsetX)"));
  assert.ok(sceneSource.includes("entry.hatSprite.y = entry.hatBaseY + bobOffset;"));
  assert.ok(sceneSource.includes("hatId: effectiveHatIdForAgent(agent),"));
  assert.ok(sceneSource.includes("const hat = hatDefinitionById(agent && agent.hatId);"));
  assert.ok(styles.includes(".hat-cycle {"));
  assert.ok(styles.includes(".hat-preview-frame {"));
});

test("navigation source depth-sorts agents and desk shell sprites by feet position instead of fixed layers", () => {
  const navigationSource = readRuntimeSource("navigation-source.ts");
  const sceneSource = readRuntimeSource("scene-source.ts");
  const renderSource = readRuntimeSource("render-source.ts");

  assert.ok(navigationSource.includes("function sceneFootDepth(y, height, bias = 0, tileSize = 16, depthBaseY = 0, depthRow = null) {"));
  assert.ok(navigationSource.includes("const depthBase = Number.isFinite(depthBaseY) ? Number(depthBaseY) : 0;"));
  assert.ok(navigationSource.includes("const relativeFootY = footY - depthBase;"));
  assert.ok(navigationSource.includes("const tileRow = Number.isFinite(depthRow) ? Number(depthRow) : Math.floor(relativeFootY / unit);"));
  assert.ok(navigationSource.includes("const intraTileY = relativeFootY - tileRow * unit;"));
  assert.ok(navigationSource.includes("return (100000 + Math.round(depthBase)) * 1000000 + (1000 + tileRow) * 1000 + Math.round(intraTileY * 10) + (Number.isFinite(bias) ? Number(bias) : 0);"));
  assert.ok(navigationSource.includes("function avatarRenderMetrics(agent) {"));
  assert.ok(navigationSource.includes("renderHeight = Number.isFinite(motionState.renderHeight) ? Number(motionState.renderHeight) : Number(motionState.height);"));
  assert.ok(navigationSource.includes("renderTopY = Number.isFinite(motionState.currentY)"));
  assert.ok(navigationSource.includes("function applyFootDepth(node, y, height, bias = 0, tileSize = 16, depthBaseY = 0, depthRow = null) {"));
  assert.ok(navigationSource.includes("if (Number.isFinite(definition.depthFootY)) {"));
  assert.ok(navigationSource.includes("Number(definition.depthFootY) - snappedHeight,"));
  assert.ok(navigationSource.includes("const fixedZ = Number.isFinite(agent.z) ? Number(agent.z) : null;"));
  assert.ok(navigationSource.includes("if (fixedZ !== null) {"));
  assert.ok(navigationSource.includes("Number.isFinite(agent.depthBaseY) ? Number(agent.depthBaseY) : 0"));
  assert.ok(navigationSource.includes("function syncMotionStateDepth(motionState) {"));
  assert.ok(navigationSource.includes("const settledAtTarget = motionState.exiting !== true"));
  assert.ok(navigationSource.includes("const effectiveDepthFootY = settledAtTarget && Number.isFinite(motionState.settledDepthFootY)"));
  assert.ok(navigationSource.includes("previousState.settledDepthFootY = Number.isFinite(avatarVisual.depthFootY) ? Number(avatarVisual.depthFootY) : null;"));
  assert.ok(navigationSource.includes("settledDepthFootY: Number.isFinite(avatarVisual.depthFootY) ? Number(avatarVisual.depthFootY) : null,"));
  assert.ok(navigationSource.includes("const depthBias = effectiveDepthBias;"));
  assert.ok(sceneSource.includes("renderer.syncMotionStateDepth(entry);"));
  assert.ok(sceneSource.includes("const renderOffsetX = Number.isFinite(entry.renderOffsetX) ? Number(entry.renderOffsetX) : 0;"));
  assert.ok(sceneSource.includes("entry.sprite.x = pixelSnap(entry.currentX + renderOffsetX);"));
  assert.ok(sceneSource.includes("entry.sprite.y = pixelSnap(entry.currentY + renderOffsetY);"));
  assert.ok(renderSource.includes("const deskDepthFootY = absoluteCellY + deskY + deskHeight;"));
  assert.ok(renderSource.includes("const chairDepthFootY = absoluteCellY + chairY + chairHeight;"));
  assert.ok(renderSource.includes("const workstationDepthFootY = absoluteCellY + workstationY + workstationHeight;"));
  assert.ok(renderSource.includes("const workstationOcclusionInset = compact ? 3 : 4;"));
  assert.ok(renderSource.includes("const workstationFrontDepthFootY = Math.max(deskDepthFootY, workstationDepthFootY) + workstationOcclusionInset;"));
  assert.ok(renderSource.includes("const workstationBoundsHeight = sceneTile * 2;"));
  assert.ok(renderSource.includes("const workstationSortFootY = stationBoundsY + workstationBoundsHeight - 1;"));
  assert.ok(renderSource.includes("const workstationSortRow = Math.floor((workstationSortFootY - depthBaseY) / sceneTile);"));
  assert.ok(renderSource.includes("depthBaseY: Number.isFinite(options.depthBaseY) ? Math.round(options.depthBaseY) : null,"));
  assert.ok(renderSource.includes("depthRow: Number.isFinite(options.depthRow) ? Math.round(options.depthRow) : null,"));
  assert.ok(renderSource.includes("enteringReveal: options.enteringReveal === true,"));
  assert.ok(renderSource.includes("const DESK_SHELL_DEPTH_BIAS = 120;"));
  assert.ok(renderSource.includes("const CHAIR_DEPTH_BIAS = 180;"));
  assert.ok(renderSource.includes("const SEATED_AVATAR_DEPTH_BIAS = 760;"));
  assert.ok(renderSource.includes("const WORKSTATION_FRONT_DEPTH_BIAS = 620;"));
  assert.ok(renderSource.includes("depthFootY: chairDepthFootY,"));
  assert.ok(renderSource.includes("depthFootY: workstationSortFootY,"));
  assert.ok(renderSource.includes("depthRow: workstationSortRow,"));
  assert.ok(renderSource.includes("const mountedWorkstationOccupant = Boolean(agent) && Boolean(options.slotId) && state !== \"blocked\";"));
  assert.ok(renderSource.includes("depthFootY: mountedWorkstationOccupant ? workstationSortFootY : null"));
  assert.ok(renderSource.includes("depthRow: mountedWorkstationOccupant ? workstationSortRow : null"));
  assert.ok(renderSource.includes("depthBias: mountedWorkstationOccupant ? SEATED_AVATAR_DEPTH_BIAS : null"));
  assert.ok(renderSource.includes("if (state === \"idle\" || state === \"done\") {"));
  assert.ok(renderSource.includes("x: seatedX,"));
  assert.ok(renderSource.includes("flip: workstationFlip"));
  assert.doesNotMatch(renderSource, /return \{ x: sideX, y: baseY, flip: workstationFlip \};/);
  assert.ok(sceneSource.includes("depthFootY: Number.isFinite(options.depthFootY) ? Math.round(options.depthFootY) : null,"));
  assert.ok(sceneSource.includes("depthBaseY: Number.isFinite(options.depthBaseY) ? Math.round(options.depthBaseY) : null,"));
  assert.ok(sceneSource.includes("depthRow: Number.isFinite(options.depthRow) ? Math.round(options.depthRow) : null,"));
  assert.ok(sceneSource.includes("depthBias: Number.isFinite(options.depthBias) ? Number(options.depthBias) : null,"));
  assert.ok(renderSource.includes("const seatedState = state === \"editing\""));
});

test("debug tiles expose visible workstation and avatar pivot markers", () => {
  const navigationSource = readRuntimeSource("navigation-source.ts");
  const renderSource = readRuntimeSource("render-source.ts");

  assert.ok(navigationSource.includes("function addDebugPivot(x, y, color) {"));
  assert.ok(navigationSource.includes(".circle(pivotX, pivotY, 4)"));
  assert.ok(navigationSource.includes(".circle(pivotX, pivotY, 2)"));
  assert.ok(renderSource.includes("pivotX: absoluteCellX + Math.round(avatarPose.x + avatarWidth / 2),"));
  assert.ok(renderSource.includes("pivotY: workstationSortFootY,"));
  assert.ok(renderSource.includes("pivotWidth: Math.round(workstationWidth)"));
});

test("workspace focus reuses compact scene geometry and grid-snapped desk starts", () => {
  const uiSource = readRuntimeSource("ui-source.ts");
  const renderSource = readRuntimeSource("render-source.ts");
  const sceneGridSource = readClientSource("scene-grid-source.ts");

  assert.ok(uiSource.includes("compact: true,"));
  assert.ok(
    sceneGridSource.includes('const deskStartColumn = Math.max('),
    "desk columns should start from a snapped tile column"
  );
  assert.ok(
    sceneGridSource.includes('const deskStartX = deskStartColumn * config.tileSize;'),
    "desk pod origins should convert the snapped column back into tile pixels"
  );
  assert.ok(
    renderSource.includes("tileHeight: 2"),
    "workstation footprint should extend one tile lower while staying top-aligned"
  );
});

test("workspace focus lets the expanded floor fill the full panel rect", () => {
  const stylesSource = readFileSync(
    join(__dirname, "../src/client/styles.css"),
    "utf8"
  ).replace(/\r\n/g, "\n");

  assert.match(
    stylesSource,
    /body\.workspace-focus \.workspace-tower,\n\s+body\.workspace-focus \.workspace-tower-single \{\n\s+width: 100%;\n\s+max-width: none;\n\s+min-height: 100%;\n\s+margin: 0;/
  );
  assert.match(
    stylesSource,
    /body\.workspace-focus \.tower-floor-body \{\n\s+min-height: 0;\n\s+height: 100%;\n\s+padding: 0;\n\s+overflow: hidden;/
  );
  assert.match(
    stylesSource,
    /body\.workspace-focus \.office-map-host \{\n\s+min-height: 0;\n\s+height: 100%;\n\s+overflow: hidden;/
  );
});

test("runtime source strips markdown formatting markers from display text", () => {
  const layoutSource = readRuntimeSource("layout-source.ts");

  assert.ok(layoutSource.includes("function stripDisplayMarkdown(value) {"));
  assert.ok(layoutSource.includes('.replace(/\\\\[([^\\\\]]+)\\\\]\\\\(([^)]+)\\\\)/g, "$1")'));
  assert.ok(layoutSource.includes('.split(String.fromCharCode(96)).join("")'));
  assert.ok(layoutSource.includes("const plainText = stripDisplayMarkdown(normalized);"));
  assert.ok(layoutSource.includes('const next = plainText.indexOf("/mnt/", index);'));
  assert.ok(layoutSource.includes("output += plainText.slice(index, next) + (cleaned || wslToWindowsPath(candidate));"));
});

test("runtime source sanitizes path-heavy labels and latest messages with the project root", () => {
  const layoutSource = readRuntimeSource("layout-source.ts");
  const renderSource = readRuntimeSource("render-source.ts");
  const uiSource = readRuntimeSource("ui-source.ts");

  assert.ok(layoutSource.includes("function compactPathyLabel(snapshot, label) {"));
  assert.ok(layoutSource.includes("return normalizeDisplayText(snapshot && snapshot.projectRoot, preferred) || preferred || \"Agent\";"));
  assert.ok(renderSource.includes("function latestAgentMessage(projectRoot, agent) {"));
  assert.ok(renderSource.includes("const message = latestAgentMessage(snapshot.projectRoot, agent);"));
  assert.ok(renderSource.includes("const hoverTitle = displayAgentLabel(snapshot, agent);"));
  assert.ok(uiSource.includes("latestAgentMessage(snapshot.projectRoot, agent)"));
});

test("runtime source only keeps finished subagents in recent sessions during the child grace window", () => {
  const layoutSource = readRuntimeSource("layout-source.ts");
  const settingsSource = readRuntimeSource("settings-source.ts");

  assert.ok(layoutSource.includes("const SUBAGENT_RECENT_SESSION_GRACE_MS = 12000;"));
  assert.ok(layoutSource.includes("function keepFinishedSubagentSession(agent) {"));
  assert.ok(layoutSource.includes("return keepFinishedSubagentSession(agent);"));
  assert.ok(settingsSource.includes("const SUBAGENT_DEPARTING_AGENT_TTL_MS = 3200;"));
  assert.ok(settingsSource.includes("function departingAgentTtlMs(agent) {"));
});

test("runtime source section files now start on function boundaries instead of continuing previous functions", () => {
  const sceneSource = readRuntimeSource("scene-source.ts");
  const uiSource = readRuntimeSource("ui-source.ts");

  assert.match(sceneSource, /^export const CLIENT_RUNTIME_SCENE_SOURCE = `\s*function buildLeadClusters/);
  assert.match(uiSource, /^export const CLIENT_RUNTIME_UI_SOURCE = `\s*function renderSessions/);
});

test("runtime source merges worktrees by repo and renders worktree badges in hover and split floor headers", () => {
  const layoutSource = readRuntimeSource("layout-source.ts");
  const renderSource = readRuntimeSource("render-source.ts");
  const sceneSource = readRuntimeSource("scene-source.ts");
  const uiSource = readRuntimeSource("ui-source.ts");
  const settingsSource = readRuntimeSource("settings-source.ts");

  assert.ok(layoutSource.includes("function mergeWorktreeProjects(projects) {"));
  assert.ok(layoutSource.includes("function inferredCodexWorktreeMetadata(projectRoot) {"));
  assert.ok(layoutSource.includes("function snapshotMatchesProjectRoot(snapshot, projectRoot) {"));
  assert.ok(layoutSource.includes("function repoIdentityForSnapshot(snapshot) {"));
  assert.ok(layoutSource.includes('return "git-repo:" + repoIdentity;'));
  assert.ok(layoutSource.includes('return "git-common:" + commonGitDir;'));
  assert.ok(layoutSource.includes("mergedProjectRoots: bucket.snapshots.map((snapshot) => snapshot.projectRoot),"));
  assert.ok(layoutSource.includes("sourceProjectRoot,"));
  assert.ok(renderSource.includes('const worktreeHtml = worktreeName'));
  assert.ok(renderSource.includes('class="agent-hover-worktree"'));
  assert.ok(renderSource.includes('agent && agent.network'));
  assert.ok(renderSource.includes('class="agent-hover-peer"'));
  assert.ok(renderSource.includes('agent.network.peerRoom ?'));
  assert.ok(!renderSource.includes('" @ " + agent.network.peerHost'));
  assert.ok(sceneSource.includes('tower-floor-title-project'));
  assert.ok(sceneSource.includes('tower-floor-title-worktree'));
  assert.ok(uiSource.includes('const selectableProjects = Boolean(state.globalSceneSettings && state.globalSceneSettings.splitWorktrees)'));
  assert.ok(uiSource.includes('...selectableProjects.map((project) => {'));
  assert.ok(settingsSource.includes("splitWorktrees: Boolean(parsed && parsed.splitWorktrees)"));
});

test("rec-room roster keeps space for recently visible resting leads that went active", () => {
  const layoutSource = readFileSync(
    join(__dirname, "../src/client/runtime/layout-source.ts"),
    "utf8"
  );
  const specSource = readFileSync(
    join(__dirname, "../../../docs/spec.md"),
    "utf8"
  );

  assert.match(
    layoutSource,
    /const effectiveLimit = Math\.max\(0, limit - reservedRecentLeadSlots\(snapshot\)\);/
  );
  assert.match(
    layoutSource,
    /slice\(0, effectiveLimit\);/
  );
  assert.match(
    specSource,
    /The rec area should keep at most the 4 most recent lead sessions visible;/,
  );
  assert.match(
    specSource,
    /If one of those visible resting leads becomes active again, older hidden leads should not pop back into the rec area just to fill that seat for a moment\./,
  );
});

test("runtime source limits visible rec-room resters to recent top-level leads", () => {
  const sceneSource = readRuntimeSource("scene-source.ts").replace(/\r\n/g, "\n");

  assert.ok(sceneSource.includes('const allRestingAgents = restingAgentsFor(snapshot, compact);'));
  assert.match(sceneSource, /\.filter\(\(agent\) =>\n\s*!agent\.parentThreadId/);
  assert.ok(sceneSource.includes(".slice(0, 4);"));
  assert.ok(sceneSource.includes('const restingAssignments = stableSceneSlotAssignments(snapshot.projectRoot, "resting", restingAgents, 4);'));
});

test("runtime source can borrow recent rec-room leads for an empty selected workspace", () => {
  const layoutSource = readRuntimeSource("layout-source.ts");
  const uiSource = readRuntimeSource("ui-source.ts");

  assert.ok(layoutSource.includes("function recentFallbackAgentsForEmptyProject(snapshot, allProjects, limit = SCENE_RECENT_LEAD_LIMIT) {"));
  assert.ok(layoutSource.includes('detail: projectPrefix + " · " + summary,'));
  assert.ok(layoutSource.includes('const fallbackAgents = recentFallbackAgentsForEmptyProject(snapshot, allProjects, recentLeadLimit);'));
  assert.ok(uiSource.includes('? viewSnapshot(selectedSnapshot, SCENE_RECENT_LEAD_LIMIT, selectableProjects)'));
  assert.ok(uiSource.includes('? viewSessionSnapshot(selectedSnapshot, SESSION_RECENT_LEAD_LIMIT, selectableProjects)'));
});

test("runtime source falls back to default rec layout when saved sofa columns overlap", () => {
  const renderSource = readRuntimeSource("render-source.ts");
  const settingsSource = readRuntimeSource("settings-source.ts");

  assert.ok(renderSource.includes("const defaultLayout = recRoomSofaLayout(compact, roomPixelWidth, baseY);"));
  assert.ok(renderSource.includes("{ ...defaultLayout.sofas[0], x: sofaColumns.left * tile, y: baseY }"));
  assert.ok(renderSource.includes("Math.abs(requestedLayout.sofas[1].x - requestedLayout.sofas[0].x) >= tile * 3"));
  assert.ok(renderSource.includes(": defaultLayout;"));
  assert.ok(renderSource.includes("const sofaWidth = Number(sofa?.sprite?.w) || layout.sofaWidth;"));
  assert.ok(renderSource.includes("const seatOffsetRatio = seatWithinSofa === 0 ? 0.18 : 0.62;"));
  assert.ok(settingsSource.includes("function stableSceneSlotAssignments(projectRoot, category, agents, maxSlots = null) {"));
  assert.ok(settingsSource.includes("|| (slotLimit !== null && slotIndex >= slotLimit)"));
  assert.ok(settingsSource.includes("if (slotLimit !== null && nextSlotIndex >= slotLimit) {"));
});

test("runtime source resolves facility providers and service tiles from startup scene definitions", () => {
  const renderSource = readRuntimeSource("render-source.ts");
  const sceneSource = readRuntimeSource("scene-source.ts");

  assert.ok(renderSource.includes("function sceneHeldItemDefinition(itemId) {"));
  assert.ok(renderSource.includes("function normalizeFurnitureFacilityProvider(item, roomWidthTiles) {"));
  assert.ok(renderSource.includes("function buildFacilityProviderModel(room, item) {"));
  assert.ok(renderSource.includes("const resolved = normalizeFurnitureItem({ ...item, column }, tileSize, room.width);"));
  assert.ok(sceneSource.includes("roomDoors: [],"));
  assert.ok(sceneSource.includes("facilities: [],"));
  assert.ok(sceneSource.includes("model.roomDoors.push({"));
  assert.ok(sceneSource.includes("model.facilities.push("));
});

test("runtime source animates sliding room doors and autonomous resting-item trips", () => {
  const sceneSource = readRuntimeSource("scene-source.ts");
  const navigationSource = readRuntimeSource("navigation-source.ts");

  assert.ok(sceneSource.includes('if (entry.autonomy && !entry.exiting && typeof renderer.updateAutonomousRestingMotion === "function") {'));
  assert.ok(sceneSource.includes('if (entry.kind === "thrown-item") {'));
  assert.ok(sceneSource.includes("renderer.roomDoorStates.forEach((doorState) => {"));
  assert.ok(sceneSource.includes("doorState.leftSprite.x = pixelSnap(doorState.baseLeftX - slide);"));
  assert.ok(navigationSource.includes("function updateAutonomousRestingMotion(motionState, now) {"));
  assert.ok(navigationSource.includes("spawnThrownHeldItem(previousState);"));
  assert.ok(navigationSource.includes("renderer.roomDoorStates.set(room.id, {"));
  assert.ok(navigationSource.includes("routeMotionStateTo("));
  assert.ok(navigationSource.includes("doorState.doorPulseUntil = performance.now() + sceneDoorConfig().holdOpenMs;"));
});

test("runtime source avoids doorway arrival animations for first-load historical sessions", () => {
  const uiSource = readRuntimeSource("ui-source.ts");

  assert.ok(uiSource.includes("enteringAgentKeys = previousKeys.size === 0 || screenshotMode"));
  assert.ok(uiSource.includes("? new Set()"));
});

test("runtime source keeps current agents in the map scene even when they are between desk and rec placement states", () => {
  const layoutSource = readRuntimeSource("layout-source.ts");
  const seatingSource = readRuntimeSource("seating-source.ts");

  assert.ok(layoutSource.includes("function isLiveSceneAgent(agent) {"));
  assert.ok(layoutSource.includes("return agent.isCurrent === true || agent.isOngoing === true || isRuntimeActiveLocalAgent(agent);"));
  assert.ok(layoutSource.includes("return shouldSeatAtWorkstation(agent) || agent.isCurrent === true;"));
  assert.ok(layoutSource.includes("const liveAgents = snapshot.agents.filter(isLiveSceneAgent);"));
  assert.ok(layoutSource.includes("const seenAgentIds = new Set();"));
  assert.match(
    seatingSource,
    /function isLiveSceneAgent\(agent\) {\n\s+if \(!agent \|\| agent\.source === "cloud" \|\| agent\.source === "presence"\) {\n\s+return false;\n\s+}\n\s+return shouldSeatAtWorkstation\(agent\) \|\| agent\.isCurrent === true(?: \|\| isRuntimeActiveLocalAgent\(agent\))?;\n\s+}/
  );
});

test("toast renderer keeps the message, file-change, and command toast classes and chrome", () => {
  const toastSource = readFileSync(
    join(__dirname, "../src/client/toast-source.ts"),
    "utf8"
  );

  assert.ok(
    toastSource.includes('const className = \\`agent-toast \\${entry.kindClass}'),
    "toast className should start from the agent-toast base class"
  );
  assert.ok(
    toastSource.includes('entry.isFileChange ? " file-change" : ""'),
    "toast renderer should keep the file-change class toggle"
  );
  assert.ok(
    toastSource.includes('entry.isCommand ? " command-window" : ""'),
    "toast renderer should keep the command-window class toggle"
  );
  assert.ok(
    toastSource.includes('!entry.isCommand && Number(entry.priority) >= NOTIFICATION_PRIORITY_MESSAGE ? " message-toast" : ""'),
    "toast renderer should keep the message-toast class toggle"
  );
  assert.ok(
    toastSource.includes('isTextMessageNotification(entry) ? " text-message-toast" : ""'),
    "toast renderer should keep the text-message-toast class toggle"
  );
  assert.ok(
    toastSource.includes('<div class="agent-toast-window-label">cmd.exe</div>'),
    "command toasts should keep the cmd.exe window chrome"
  );
  assert.ok(
    toastSource.includes('<div class="agent-toast-command-line">'),
    "command toasts should keep per-line command rendering"
  );
  assert.ok(
    toastSource.includes('<span class="agent-toast-delta add">+\\${line.linesAdded}</span>'),
    "file-change toasts should keep added-line deltas"
  );
  assert.ok(
    toastSource.includes('<span class="agent-toast-delta remove">-\\${line.linesRemoved}</span>'),
    "file-change toasts should keep removed-line deltas"
  );
});

test("toast runtime preserves read command summaries and text-message priority", () => {
  const renderSource = readRuntimeSource("render-source.ts").replace(/\r\n/g, "\n");
  const toastSource = readFileSync(
    join(__dirname, "../src/client/toast-source.ts"),
    "utf8"
  ).replace(/\r\n/g, "\n");

  assert.match(
    renderSource,
    /if \(executable === "sed" \|\| executable === "cat" \|\| executable === "head" \|\| executable === "tail" \|\| executable === "less" \|\| executable === "more" \|\| executable === "bat"\) {\n\s+title = "Read " \+ firstPathLabel;/,
  );
  assert.match(
    renderSource,
    /else if \(executable === "rg" \|\| executable === "grep"\) {\n\s+title =\n\s+pathTokens\.length > 1 \? "Exploring " \+ pathTokens\.length \+ " files"\n\s+: firstPath \? "Search " \+ firstPathLabel\n\s+: "Search files";/,
  );
  assert.match(
    renderSource,
    /else if \(executable === "ls" \|\| executable === "find" \|\| executable === "tree"\) {\n\s+title =\n\s+pathTokens\.length > 1 \? "Exploring " \+ pathTokens\.length \+ " files"\n\s+: firstPath \? "Explore " \+ cleanReportedPath\(snapshot\.projectRoot, firstPath\)\n\s+: "Explore files";/,
  );
  assert.ok(
    renderSource.includes("if (latestMessageChanged && !typedMessageEvent) {\n          return {"),
    "latest message fallback should only run when no typed message event is available"
  );
  assert.ok(
    renderSource.includes('isTextMessage: true'),
    "latest message notifications should still be marked as text messages"
  );
  assert.ok(
    renderSource.includes('priority: NOTIFICATION_PRIORITY_MESSAGE'),
    "latest message notifications should still use message priority"
  );
  assert.ok(
    renderSource.includes("if (agentHasTypedEvent(snapshot, agent)) {\n          return null;\n        }"),
    "typed events should suppress the summary-diff notification path so event-native toasts surface first"
  );
  assert.ok(
    renderSource.includes("function shouldSuppressHistoricalHydrationNotification(snapshot, agent, previous) {"),
    "render runtime should define a historical hydration suppression helper"
  );
  assert.ok(
    toastSource.includes("if (shouldSuppressHistoricalHydrationNotification(snapshot, agent, previous)) {\n              continue;\n            }"),
    "agent-summary toasts should skip stale first-seen hydrate agents"
  );
  assert.ok(
    toastSource.includes("if (shouldSuppressHistoricalHydrationNotification(snapshot, agent, null)) {\n              continue;\n            }"),
    "typed event toasts should skip stale first-seen hydrate agents"
  );
});

test("typed snapshot events still allow message toasts even when the agent is no longer current", () => {
  const toastSource = readFileSync(
    join(__dirname, "../src/client/toast-source.ts"),
    "utf8"
  );

  assert.match(
    toastSource,
    /if \(\n?\s*!agent\.isCurrent\n?\s*&& agent\.state !== "waiting"\n?\s*&& agent\.state !== "blocked"\n?\s*&& event\.kind !== "message"\n?\s*&& !\(event\.kind === "tool" && event\.itemType === "webSearch"\)\n?\s*\) \{/,
  );
});

test("message toasts only clear older toasts for the same agent", () => {
  const toastSource = readFileSync(
    join(__dirname, "../src/client/toast-source.ts"),
    "utf8"
  ).replace(/\r\n/g, "\n");

  assert.ok(
    toastSource.includes("function pruneNotificationsForAgent(entry) {"),
    "toast runtime should define a same-agent prune helper for message toasts"
  );
  assert.match(
    toastSource,
    /return candidate\.projectRoot !== entry\.projectRoot \|\| candidate\.key !== entry\.key;/
  );
  assert.ok(
    toastSource.includes("if (priority >= NOTIFICATION_PRIORITY_MESSAGE) {\n          pruneNotificationsForAgent(entry);\n        }"),
    "message toasts should prune only same-agent toasts before enqueue"
  );
  assert.equal(
    toastSource.includes("if (priority >= NOTIFICATION_PRIORITY_MESSAGE) {\n          notifications = [];\n        }"),
    false,
    "message toasts should not clear the global notification list"
  );
});

test("toast notifications use the merged worktree view so unsplit floors keep matching scene anchors", () => {
  const multiplayerSource = readClientSource("multiplayer-source.ts");

  assert.match(
    multiplayerSource,
    /function notificationFleetView\(fleet\) {\n\s+if \(!fleet\) {\n\s+return null;\n\s+}\n\s+return {\n\s+\.\.\.fleet,\n\s+projects: mergeWorktreeProjects\(Array\.isArray\(fleet\.projects\) \? fleet\.projects : \[\]\)\n\s+};\n\s+}/
  );
  assert.match(
    multiplayerSource,
    /const previousNotificationFleet = notificationFleetView\(previousFleet\);\n\s+const nextNotificationFleet = notificationFleetView\(fleet\);\n\s+queueSnapshotEvents\(previousNotificationFleet, nextNotificationFleet\);\n\s+queueAgentNotifications\(previousNotificationFleet, nextNotificationFleet\);/
  );
});

test("boss relationship arrows are hover-only curved overlays with arrowheads", () => {
  const navigationSource = readRuntimeSource("navigation-source.ts");
  const specSource = readFileSync(
    join(__dirname, "../../../docs/spec.md"),
    "utf8"
  );

  assert.ok(navigationSource.includes(".bezierCurveTo(control1X, control1Y, control2X, control2Y, line.x2, line.y2)"));
  assert.ok(navigationSource.includes("const arrowHead = new PIXI.Graphics()"));
  assert.ok(navigationSource.includes("state.hoveredRelationshipBossKey"));
  assert.match(
    specSource,
    /Boss-to-subagent relationship arrows should only appear when the user is hovering or focusing that boss in the scene;/,
  );
});

test("spec defines door-based arrivals and departures for visible agents", () => {
  const specSource = readFileSync(
    join(__dirname, "../../../docs/spec.md"),
    "utf8"
  );

  assert.match(
    specSource,
    /A newly visible active agent should enter from the room door and walk to its assigned workstation\./,
  );
  assert.match(
    specSource,
    /If a resting lead becomes active again, it should leave its rec-area seat and walk to its newly assigned workstation instead of despawning and respawning\./,
  );
  assert.match(
    specSource,
    /When an agent truly leaves the visible scene, it should walk back out through the room door\./,
  );
});

test("runtime source only animates exit ghosts for explicit departures and dedupes them", () => {
  const navigationSource = readRuntimeSource("navigation-source.ts");
  const uiSource = readRuntimeSource("ui-source.ts");
  const layoutSource = readRuntimeSource("layout-source.ts");
  const settingsSource = readRuntimeSource("settings-source.ts");

  assert.ok(navigationSource.includes("const departingAgentKeys = new Set(departingAgents.map((agent) => agent.key));"));
  assert.ok(navigationSource.includes("!motionState || currentAgentKeys.has(key) || motionState.exiting || !departingAgentKeys.has(key)"));
  assert.ok(uiSource.includes("const existingGhost = departingAgents.find((ghost) => ghost.key === key) || null;"));
  assert.ok(uiSource.includes("existingGhost.expiresAt = now + departingAgentTtlMs(entry.agent);"));
  assert.ok(settingsSource.includes("const HISTORICAL_HYDRATION_SUPPRESS_MS = 30000;"));
  assert.ok(layoutSource.includes("function agentLooksHistoricallyHydrated(projectRoot, agent) {"));
  assert.ok(uiSource.includes("markProjectHydrated(snapshot.projectRoot, now);"));
  assert.ok(uiSource.includes("return !(entry && agentLooksHistoricallyHydrated(entry.projectRoot, entry.agent));"));
});

test("runtime source preserves exit ghosts across scene refreshes and reuses the same exit builder", () => {
  const navigationSource = readRuntimeSource("navigation-source.ts");
  const sceneSource = readRuntimeSource("scene-source.ts");

  assert.ok(navigationSource.includes("function buildExitGhostMotion(key, motionState, roomNavigation, reservations) {"));
  assert.ok(navigationSource.includes("if (!motionState || motionState.exiting !== true || currentAgentKeys.has(key) || renderer.motionStates.has(key)) {"));
  assert.ok(navigationSource.includes("const preservedExitMotion = buildExitGhostMotion(key, motionState, roomNavigation, reservedAgentTiles);"));
  assert.ok(navigationSource.includes("const ghostMotion = buildExitGhostMotion(key, motionState, roomNavigation, reservedAgentTiles);"));
  assert.ok(sceneSource.includes("entry.exitFadeAlpha = entry.sprite.alpha;"));
});

test("runtime source turns room changes into old-room exits plus new-room door entries and ignores tiny same-slot retargets", () => {
  const navigationSource = readRuntimeSource("navigation-source.ts");

  assert.ok(navigationSource.includes("function shouldReuseMotionTarget(previousState, agent, preserveAutonomyRoute = false) {"));
  assert.ok(navigationSource.includes("const distance = motionTargetDistance(previousState, agent);"));
  assert.ok(navigationSource.includes("if (sameSlotAssignment(previousState, agent)) {"));
  assert.ok(navigationSource.includes("const previousRoomState = previousMotionState && previousMotionState.roomId !== agent.roomId"));
  assert.ok(navigationSource.includes("const enteringFromDoor = !previousMotionState"));
  assert.ok(navigationSource.includes("const transitionGhostKey = agentKey + \"::transition-exit::\" + previousRoomState.roomId;"));
  assert.ok(navigationSource.includes("const transitionGhost = buildExitGhostMotion(transitionGhostKey, previousRoomState, roomNavigation, reservations);"));
});
