import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { existsSync, rmSync as rmSyncImmediate } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";

import type { PresenceEntry, PresenceRoster } from "@codex-agents-office/core";
import { startWebServer } from "@codex-agents-office/web";

interface DemoPreviewOptions {
  host: string;
  port: number;
  keep: boolean;
  durationMs: number;
}

interface DemoStage {
  afterMs: number;
  agents: PresenceEntry[];
  files?: Record<string, string>;
}

function parseDemoPreviewArgs(args: string[]): DemoPreviewOptions {
  let port = 4181;
  let host = "127.0.0.1";
  let keep = false;
  let durationMs = 75_000;

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === "--port" && args[index + 1]) {
      port = Number.parseInt(args[index + 1], 10);
      index += 1;
      continue;
    }
    if (arg === "--host" && args[index + 1]) {
      host = args[index + 1];
      index += 1;
      continue;
    }
    if (arg === "--duration" && args[index + 1]) {
      const seconds = Number.parseFloat(args[index + 1]);
      durationMs = Number.isFinite(seconds) && seconds > 0 ? Math.round(seconds * 1000) : 0;
      index += 1;
      continue;
    }
    if (arg === "--keep") {
      keep = true;
    }
  }

  return {
    host,
    port: Number.isFinite(port) ? port : 4181,
    keep,
    durationMs
  };
}

async function writeTextFile(filePath: string, content: string): Promise<void> {
  await mkdir(dirname(filePath), { recursive: true });
  await writeFile(filePath, content, "utf8");
}

function isoAt(baseMs: number, offsetMs: number): string {
  return new Date(baseMs + offsetMs).toISOString();
}

function demoPresence(
  baseMs: number,
  offsetMs: number,
  input: Omit<PresenceEntry, "updatedAt">
): PresenceEntry {
  return {
    ...input,
    updatedAt: isoAt(baseMs, offsetMs)
  };
}

function demoTemplateFiles(): Record<string, string> {
  return {
    "package.json": `{
  "name": "office-preview-app",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "test:preview": "vitest run"
  }
}
`,
    "README.md": `# Office Preview App

This is a disposable fake app generated by \`codex-agents-office demo preview\`.

It exists only to drive the office renderer with believable rooms, files, demo agents, and demo skills.
Stop the preview command to remove this workspace unless it was launched with \`--keep\`.
`,
    "src/app/main.ts": `import { renderHeroPanel } from "../ui/HeroPanel";

export function bootPreviewApp(): string {
  return renderHeroPanel("Ship the preview office");
}
`,
    "src/ui/HeroPanel.tsx": `export function renderHeroPanel(title: string): string {
  return \`<section class="hero-panel"><h1>\${title}</h1><p>Pixel office preview workspace.</p></section>\`;
}
`,
    "src/ui/StatusPill.tsx": `export function renderStatusPill(label: string): string {
  return \`<span class="status-pill">\${label}</span>\`;
}
`,
    "src/api/catalog.ts": `export interface FeatureCard {
  id: string;
  title: string;
}

export const previewCatalog: FeatureCard[] = [
  { id: "office-map", title: "Office Map" },
  { id: "session-panel", title: "Session Panel" }
];
`,
    "src/api/seed.ts": `export async function seedPreviewData(): Promise<void> {
  return Promise.resolve();
}
`,
    "tests/preview.spec.ts": `describe("preview app", () => {
  it("renders a hero", () => {
    expect(true).toBe(true);
  });
});
`,
    "docs/release-checklist.md": `# Release Checklist

- confirm office map renders
- confirm session panel reflects live state
- confirm approval/input queue remains readable
`,
    ".codex/agents/preview-orchestrator.toml": `name = "preview_orchestrator"
description = "Lead demo agent that coordinates the fake launch workspace and hands work to the demo specialists."
sandbox_mode = "workspace-write"
developer_instructions = """
Keep the preview believable and lightweight.
Delegate UI polish, API cleanup, and release checks to the sibling preview agents.
Keep all edits inside this disposable preview workspace.
"""
nickname_candidates = ["Orion", "North", "Lead"]
`,
    ".codex/agents/preview-ui-builder.toml": `name = "preview_ui_builder"
description = "Demo UI worker that tweaks the fake launch hero and status components."
sandbox_mode = "workspace-write"
developer_instructions = """
Stay in src/ui and src/app.
Make tiny visual edits that keep the preview readable in the office map.
"""
nickname_candidates = ["Nova", "Bloom", "Glimmer"]
`,
    ".codex/agents/preview-api-worker.toml": `name = "preview_api_worker"
description = "Demo worker that adjusts the fake preview catalog and seed logic."
sandbox_mode = "workspace-write"
developer_instructions = """
Stay in src/api.
Focus on believable fake app data and simple command/test style updates.
"""
nickname_candidates = ["Relay", "Sol", "Echo"]
`,
    ".codex/agents/preview-qa-guardian.toml": `name = "preview_qa_guardian"
description = "Demo validator that checks the fake preview app and reports release blockers."
sandbox_mode = "read-only"
developer_instructions = """
Read tests and docs only.
Report concise release-check findings for the preview flow.
"""
nickname_candidates = ["Ivy", "Beacon", "Check"]
`,
    ".codex/skills/preview-ui-pass/SKILL.md": `# Preview UI Pass

Use this when the preview workspace needs a believable front-end polish loop.

## Focus

- keep edits inside \`src/ui\` and \`src/app\`
- tighten copy and small component structure only
- do not introduce framework churn
`,
    ".codex/skills/preview-release-check/SKILL.md": `# Preview Release Check

Use this when the preview workspace needs a fake release readiness pass.

## Focus

- inspect \`tests/\` and \`docs/release-checklist.md\`
- summarize blockers clearly
- prefer short, concrete release language
`,
    ".codex-agents/rooms.xml": `<?xml version="1.0" encoding="UTF-8"?>
<agentOffice version="1">
  <room id="root" name="Preview App" path="." x="0" y="0" width="24" height="16">
    <room id="app" name="App Shell" path="src/app" x="1" y="7" width="7" height="5" />
    <room id="ui" name="UI" path="src/ui" x="8" y="7" width="7" height="5" />
    <room id="api" name="API" path="src/api" x="15" y="7" width="8" height="5" />
    <room id="qa" name="QA" path="tests" x="14" y="1" width="9" height="5" />
    <room id="docs" name="Docs" path="docs" x="1" y="1" width="6" height="5" />
  </room>
</agentOffice>
`
  };
}

function stageFileUpdates(): Array<Record<string, string>> {
  return [
    {},
    {
      "src/ui/HeroPanel.tsx": `export function renderHeroPanel(title: string): string {
  return \`<section class="hero-panel polished"><h1>\${title}</h1><p>Live office preview with demo specialists.</p></section>\`;
}
`,
      "docs/release-checklist.md": `# Release Checklist

- verify hover cards stay readable
- verify the office map holds one lead and several workers
- verify the preview cleans itself up when the run ends
`
    },
    {
      "src/api/catalog.ts": `export interface FeatureCard {
  id: string;
  title: string;
  owner: string;
}

export const previewCatalog: FeatureCard[] = [
  { id: "office-map", title: "Office Map", owner: "preview_ui_builder" },
  { id: "session-panel", title: "Session Panel", owner: "preview_orchestrator" },
  { id: "release-check", title: "Release Check", owner: "preview_qa_guardian" }
];
`,
      "tests/preview.spec.ts": `describe("preview app", () => {
  it("keeps the preview green", () => {
    expect(["office-map", "session-panel"]).toContain("office-map");
  });
});
`
    },
    {
      "src/api/seed.ts": `export async function seedPreviewData(): Promise<void> {
  await Promise.resolve();
}
`,
      "README.md": `# Office Preview App

This disposable workspace is mid-flight in the office preview harness.

The orchestrator has handed UI polish, API cleanup, and release review to the demo specialists.
`
    }
  ];
}

function buildDemoStages(projectRoot: string): DemoStage[] {
  const baseMs = Date.now();
  const appDir = join(projectRoot, "src/app");
  const uiDir = join(projectRoot, "src/ui");
  const apiDir = join(projectRoot, "src/api");
  const qaDir = join(projectRoot, "tests");
  const docsDir = join(projectRoot, "docs");
  const files = stageFileUpdates();

  return [
    {
      afterMs: 0,
      files: files[0],
      agents: [
        demoPresence(baseMs, 0, {
          id: "preview-lead",
          label: "Preview Orchestrator",
          role: "lead",
          state: "planning",
          detail: "Breaking the fake launch app into UI, API, and release passes.",
          cwd: appDir,
          appearanceId: "sun"
        }),
        demoPresence(baseMs, 0, {
          id: "preview-ui",
          label: "Preview UI Builder",
          role: "worker",
          state: "editing",
          detail: "Polishing HeroPanel.tsx for the office preview.",
          cwd: uiDir,
          appearanceId: "rose"
        }),
        demoPresence(baseMs, 0, {
          id: "preview-api",
          label: "Preview API Worker",
          role: "worker",
          state: "running",
          detail: "Seeding src/api for believable demo data.",
          cwd: apiDir,
          appearanceId: "ocean"
        }),
        demoPresence(baseMs, 0, {
          id: "preview-qa",
          label: "Preview QA Guardian",
          role: "explorer",
          state: "validating",
          detail: "Checking the fake preview spec before handoff.",
          cwd: qaDir,
          appearanceId: "mint"
        }),
        demoPresence(baseMs, 0, {
          id: "preview-scribe",
          label: "Preview Release Scribe",
          role: "scribe",
          state: "thinking",
          detail: "Drafting the release checklist for the preview run.",
          cwd: docsDir,
          appearanceId: "iris"
        })
      ]
    },
    {
      afterMs: 9_000,
      files: files[1],
      agents: [
        demoPresence(baseMs, 9_000, {
          id: "preview-lead",
          label: "Preview Orchestrator",
          role: "lead",
          state: "delegating",
          detail: "Handed UI polish to preview_ui_builder and API cleanup to preview_api_worker.",
          cwd: appDir,
          appearanceId: "sun"
        }),
        demoPresence(baseMs, 9_000, {
          id: "preview-ui",
          label: "Preview UI Builder",
          role: "worker",
          state: "editing",
          detail: "Tightening hero copy and status-pill spacing.",
          cwd: uiDir,
          appearanceId: "rose"
        }),
        demoPresence(baseMs, 9_000, {
          id: "preview-api",
          label: "Preview API Worker",
          role: "worker",
          state: "editing",
          detail: "Adding release ownership fields to the fake catalog.",
          cwd: apiDir,
          appearanceId: "ocean"
        }),
        demoPresence(baseMs, 9_000, {
          id: "preview-qa",
          label: "Preview QA Guardian",
          role: "explorer",
          state: "scanning",
          detail: "Reading preview specs and release notes for mismatches.",
          cwd: qaDir,
          appearanceId: "mint"
        }),
        demoPresence(baseMs, 9_000, {
          id: "preview-scribe",
          label: "Preview Release Scribe",
          role: "scribe",
          state: "editing",
          detail: "Refreshing docs/release-checklist.md for the preview walkthrough.",
          cwd: docsDir,
          appearanceId: "iris"
        })
      ]
    },
    {
      afterMs: 18_000,
      files: files[2],
      agents: [
        demoPresence(baseMs, 18_000, {
          id: "preview-lead",
          label: "Preview Orchestrator",
          role: "lead",
          state: "waiting",
          detail: "Waiting on final release-note wording from the docs pass.",
          cwd: appDir,
          appearanceId: "sun"
        }),
        demoPresence(baseMs, 18_000, {
          id: "preview-ui",
          label: "Preview UI Builder",
          role: "worker",
          state: "done",
          detail: "UI polish landed for HeroPanel.tsx and StatusPill.tsx.",
          cwd: uiDir,
          appearanceId: "rose"
        }),
        demoPresence(baseMs, 18_000, {
          id: "preview-api",
          label: "Preview API Worker",
          role: "worker",
          state: "validating",
          detail: "Running the fake preview validation pass against src/api and tests.",
          cwd: apiDir,
          appearanceId: "ocean"
        }),
        demoPresence(baseMs, 18_000, {
          id: "preview-qa",
          label: "Preview QA Guardian",
          role: "explorer",
          state: "running",
          detail: "Checking the preview spec after the catalog update.",
          cwd: qaDir,
          appearanceId: "mint"
        }),
        demoPresence(baseMs, 18_000, {
          id: "preview-scribe",
          label: "Preview Release Scribe",
          role: "scribe",
          state: "editing",
          detail: "Finalizing the release checklist wording for the lead.",
          cwd: docsDir,
          appearanceId: "iris"
        })
      ]
    },
    {
      afterMs: 30_000,
      files: files[3],
      agents: [
        demoPresence(baseMs, 30_000, {
          id: "preview-lead",
          label: "Preview Orchestrator",
          role: "lead",
          state: "thinking",
          detail: "Approval landed. Pulling the fake release story together for the office pass.",
          cwd: appDir,
          appearanceId: "sun"
        }),
        demoPresence(baseMs, 30_000, {
          id: "preview-ui",
          label: "Preview UI Builder",
          role: "worker",
          state: "done",
          detail: "UI pass completed and handed back to the lead.",
          cwd: uiDir,
          appearanceId: "rose"
        }),
        demoPresence(baseMs, 30_000, {
          id: "preview-api",
          label: "Preview API Worker",
          role: "worker",
          state: "done",
          detail: "Catalog and seed flow look ready for the fake handoff.",
          cwd: apiDir,
          appearanceId: "ocean"
        }),
        demoPresence(baseMs, 30_000, {
          id: "preview-qa",
          label: "Preview QA Guardian",
          role: "explorer",
          state: "done",
          detail: "Preview validation pass is green.",
          cwd: qaDir,
          appearanceId: "mint"
        }),
        demoPresence(baseMs, 30_000, {
          id: "preview-scribe",
          label: "Preview Release Scribe",
          role: "scribe",
          state: "done",
          detail: "Release notes and checklist are ready for the walkthrough.",
          cwd: docsDir,
          appearanceId: "iris"
        })
      ]
    }
  ];
}

async function writePresenceRoster(projectRoot: string, agents: PresenceEntry[]): Promise<void> {
  const roster: PresenceRoster = {
    version: 1,
    agents
  };
  await writeTextFile(join(projectRoot, ".codex-agents/presence.json"), JSON.stringify(roster, null, 2) + "\n");
}

async function createDemoWorkspace(): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), "codex-agents-office-preview-"));
  const templates = demoTemplateFiles();
  for (const [relativePath, content] of Object.entries(templates)) {
    await writeTextFile(join(root, relativePath), content);
  }
  return root;
}

async function applyStage(projectRoot: string, stage: DemoStage): Promise<void> {
  if (stage.files) {
    for (const [relativePath, content] of Object.entries(stage.files)) {
      await writeTextFile(join(projectRoot, relativePath), content);
    }
  }
  await writePresenceRoster(projectRoot, stage.agents);
}

export async function runDemoPreview(args: string[]): Promise<void> {
  const options = parseDemoPreviewArgs(args);
  const projectRoot = await createDemoWorkspace();
  const stages = buildDemoStages(projectRoot);
  const timers = new Set<NodeJS.Timeout>();
  let cleaned = false;

  const cleanup = () => {
    if (cleaned) {
      return;
    }
    cleaned = true;
    for (const timer of timers) {
      clearTimeout(timer);
    }
    timers.clear();
    if (!options.keep && existsSync(projectRoot)) {
      rmSyncImmediate(projectRoot, { recursive: true, force: true });
    }
  };

  process.once("SIGINT", cleanup);
  process.once("SIGTERM", cleanup);
  process.once("exit", cleanup);

  await applyStage(projectRoot, stages[0]);
  for (const stage of stages.slice(1)) {
    const timer = setTimeout(() => {
      void applyStage(projectRoot, stage);
      timers.delete(timer);
    }, stage.afterMs);
    timers.add(timer);
  }

  console.log(`Preview workspace: ${projectRoot}`);
  console.log(`Preview URL: http://${options.host}:${options.port}/?project=${encodeURIComponent(projectRoot)}`);
  console.log("This run creates a disposable fake app with demo agents, demo skills, and a scripted office workflow.");
  console.log(options.keep ? "Workspace cleanup is disabled for this run (--keep)." : "Workspace will be removed when the preview stops.");
  if (options.durationMs > 0) {
    console.log(`Preview duration: ${Math.round(options.durationMs / 1000)}s`);
  } else {
    console.log("Preview duration: until interrupted");
  }

  await startWebServer([projectRoot, "--port", String(options.port), "--host", options.host]);

  if (options.durationMs > 0) {
    const timer = setTimeout(async () => {
      timers.delete(timer);
      cleanup();
      process.exit(0);
    }, options.durationMs);
    timers.add(timer);
  }

  await new Promise<void>(() => {});
}

export async function deletePreviewWorkspace(projectRoot: string): Promise<void> {
  await rm(resolve(projectRoot), { recursive: true, force: true });
}
